version: '3'
services:

  db:
    image: mysql:5.7
    container_name: db-container
    volumes:
      - db-volume:/var/lib/mysql
    ports:
      - "6606:3306"
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=guoziwei
      - MYSQL_DATABASE=live
    networks:
      - db_network

  nginx:
    container_name: nginx-container
    image: nginx:latest
    restart: always
    ports:
      - "80:80"
    volumes:
      - static-volume:/code/collected_static
      - ./config/nginx:/etc/nginx/conf.d
    depends_on:
      - api
    networks:
      - web_network

  api:
    container_name: api-container
    build: ./api
    restart: always
    command: bash -c "python3 manage.py collectstatic --no-input && python3 manage.py migrate && gunicorn --timeout=30 --workers=4 --bind :80 LiveTVServer.wsgi:application"
    depends_on:
      - db
    volumes:
      - static-volume:/code/collected_static
    networks:
      - web_network
      - db_network

    #     auto migrate django
#  migration:
#    build: ./api
#    command:
#      - /bin/sh
#      - -c
#      - |
#        python manage.py collectstatic --noinput
#        python manage.py migrate
#        python manage.py makemigrations musics
#        python manage.py migrate
#    volumes:
#      - api_data:/docker_api
#    depends_on:
#      - db

networks:
  web_network:
    driver: bridge
  db_network:
    driver: bridge

volumes:
  static-volume:
  db-volume:

