# Generated by Django 3.0 on 2019-12-12 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Live',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('publish_date', models.DateTimeField()),
                ('update_date', models.DateTimeField()),
                ('url', models.TextField()),
                ('category', models.IntegerField(choices=[(0, '央视'), (1, '地方'), (2, '港澳'), (3, '台湾'), (4, '国际'), (5, '体育'), (6, '影视'), (7, '少儿'), (8, '新闻')], default=0)),
            ],
        ),
    ]
