# Generated by Django 3.0 on 2019-12-12 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='live',
            name='publish_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='live',
            name='update_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
